### ISSUE TITLE
Quick Start on MacOS using docker-machine

### ISSUE THREAD

**Issue by nik-ffm** [bmwcarit/barefoot#1]
I really like your MapMatching Algorithm Proposal and wanted to try. Since it took me some time to make it work using docker-machine (should be kind of similar for boot2docker) I want to share my insights for others:

First you should consider creating yourself a new docker-machine since the container requires even in standard installation 6.5GB. This command creates a new instance of 30GB using virtualbox.
`docker-machine create -d virtualbox --virtualbox-disk-size "30000" default`

Next follow the Quick Start Guide regarding the Map server but:
 - leave out the sudo in all commands
 - At Step 4: Exchange `172.17.0.0` for the ip you get using `docker-machine ip <name of docker-machine instance>`

Having your container up you will need to edit the PostGIS security configuration (of course, this configuration is only for testing, don't use it for production):
`echo host all  all    0.0.0.0/0  md5  >> /etc/postgresql/9.3/main/pg_hba.conf`
You will need to restart the container or at least PostGIS for the changes to take place

After this change the host ip in `config/oberbayern.properties` again for the ip of your docker-machine instance ( `docker-machine ip <name of docker-machine instance>`)

Now you can follow the second part of the quick start regarding map matching server (probably you will need to install netcat: `brew install netcat`)

**Comment by smattheis** [comment]
How have you made Barefoot's Docker image available in the VirtualBox machine, as well as the mounted directories? - Did you login to the VirtualBox machine via SSH `docker-machine ssh <name of docker-machine instance>`, checked out the Barefoot repository and built the Docker image from within the VirtualBox machine? Starting and stopping the VirtualBox machine and the map server container would then still work from your host system, right?

(I plan to create a GitHub wiki at the beginning of next year, which involves a split of the current manual page into reference documentation, a “roadmap" for further development, and hands-on tutorials, which will include e.g. the installation of the Barefoot map server on Docker Machine, deployment of Barefoot in Apache Storm, Apache Spark, Apache Hadoop, etc. Also, I will think about a Docker Compose setup for the map server and the stand-alone map matching server.)

**Comment by nik-ffm** [comment]
Hi smattheis,
your plans sound great. I am using barefoot within my master thesis, so I will work with it quite a lot I think. Let me know if i can help you.

Regarding the shared folders: Yes, I mount them just the way you do natively. Starting and stopping docker-machine isn't a problem.

**Comment by smattheis** [comment]
Thanks again for the feedback! Of course, you can help. :+1: I would also be interested in what you're doing for your thesis. For that purpose, would be nice if you send me an email. You can find my email address in any source file of the repository.
