### ISSUE TITLE
Server failing to load map

### ISSUE THREAD

**Issue by sergiormpereira** [bmwcarit/barefoot#131]
Hello, I am trying to use Map Matching with the south part of USA (us-south-latest.osm.pbf). I manage to create the docker with the database, and then I tried to launch the server as:

java -Xmx32g -jar target/barefoot-0.1.5-matcher-jar-with-dependencies.jar --geojson config/server.properties config/south_us.properties

I put the flag -Xmx32g because it was first raising an issue of heap space, which I manage to pass with that flag.

My server.properties (default parameters):
server.port=1234
server.timeout.request=15000
server.timeout.response=60000
server.connections=20
matcher.sigma=10
matcher.lambda=0.0
matcher.distance.max=15000
matcher.radius.max=200
matcher.interval.min=1000
matcher.distance.min=0
matcher.threads=8
matcher.shortenturns=true

south_us.properties:
database.host=localhost
database.port=5432
database.name=barefoot_us_south
database.table=bfmap_ways
database.user=osmuser
database.password=pass
database.road-types=./map/tools/road-types.json

The exception that I got is attached as an image.

I tried with Berlin and the server launched normally.

I also tried to query the database for the number of rows as "docker exec barefoot_us_south psql -h localhost -U osmuser -d barefoot_us_south -c "select count(*) from bfmap_ways ;"", and got 17952685, so, when the server is launched it raises the exception before loading the whole database.
Do you have an idea of what may be the problem?

Thanks!

![screenshot 2019-01-23 at 14 55 12](https://user-images.githubusercontent.com/20443132/51615273-514da100-1f1f-11e9-8812-4dbcd98d6c78.png)

**Comment by smattheis** [comment]
Try deleting the bfmap file in the directory that was created before and start the server again to load from the map server instead the file. (Maybe the bfmap file was corrupted when you loaded it the first time where you got the heap space problem.)

**Comment by sergiormpereira** [comment]
It worked! Thanks a lot for the super fast answer  :)
