### ISSUE TITLE
cannot see the result in http://localhost:3000 

### ISSUE THREAD

**Issue by biallen** [bmwcarit/barefoot#132]
im  soryy，i meet other problem . when i run 
 python util/submit/batch.py --host 127.0.0.1 --port 8888  --file src/test/resources/com/bmwcarit/barefoot/matcher/x0001-015.json。
 return  SUCCESS;

but  http://localhost:3000 ,have no result;

the matcher server and  TrackerServer run same server,so  i  change the port .
===========
server.properties 
server.port=5678
server.timeout.request=15000
server.timeout.response=60000
server.connections=20
matcher.sigma=10
matcher.lambda=0.0
matcher.distance.max=15000
matcher.radius.max=200
matcher.interval.min=1000
matcher.distance.min=0
matcher.threads=8
matcher.shortenturns=true

-------------------

tracker.properties

server.port=8888
server.timeout.request=1000
server.timeout.response=10000
server.connections=100
matcher.sigma=10
matcher.lambda=0.0
matcher.distance.max=5000
matcher.radius.max=200
matcher.interval.min=1000
matcher.distance.min=0
matcher.threads=8
matcher.shortenturns=true
tracker.state.ttl=60
tracker.port=1235

=========
the json data ：
[{"point":"POINT(11.564388282625075 48.16350662940509)","time":"2014-09-10 06:54:07+0200","id":"\\x0001"},{"point":"POINT(11.563678490482323 48.16198390379898)","time":"2014-09-10 06:54:22+0200","id":"\\x0001"},{"point":"POINT(11.563473064247667 48.16122306758928)","time":"2014-09-10 06:54:37+0200","id":"\\x0001"},{"point":"POINT(11.563349010292418 48.16097334859303)","time":"2014-09-10 06:54:52+0200","id":"\\x0001"},{"point":"POINT(11.56211307019753 48.16105053673302)","time":"2014-09-10 06:55:07+0200","id":"\\x0001"},{"point":"POINT(11.562087955592313 48.16105310550876)","time":"2014-09-10 06:55:22+0200","id":"\\x0001"},{"point":"POINT(11.56050052334351 48.16132139354706)","time":"2014-09-10 06:55:37+0200","id":"\\x0001"},{"point":"POINT(11.55861940673031 48.16146246902161)","time":"2014-09-10 06:55:52+0200","id":"\\x0001"},{"point":"POINT(11.55781684760151 48.16150944854922)","time":"2014-09-10 06:56:07+0200","id":"\\x0001"},{"point":"POINT(11.554951837127055 48.161525422789964)","time":"2014-09-10 06:56:22+0200","id":"\\x0001"},{"point":"POINT(11.553457873233345 48.16153005345599)","time":"2014-09-10 06:56:37+0200","id":"\\x0001"},{"point":"POINT(11.553457873233345 48.16153005345599)","time":"2014-09-10 06:56:52+0200","id":"\\x0001"},{"point":"POINT(11.553457873233345 48.16153005345599)","time":"2014-09-10 06:57:07+0200","id":"\\x0001"},{"point":"POINT(11.55233027283797 48.16151270819414)","time":"2014-09-10 06:57:22+0200","id":"\\x0001"},{"point":"POINT(11.549709459760114 48.16086527596004)","time":"2014-09-10 06:57:37+0200","id":"\\x0001"},{"point":"POINT(11.547606473265642 48.1597561817289)","time":"2014-09-10 06:57:52+0200","id":"\\x0001"},{"point":"POINT(11.547570796486772 48.15974397345911)","time":"2014-09-10 06:58:07+0200","id":"\\x0001"},{"point":"POINT(11.547570796486772 48.15974397345911)","time":"2014-09-10 06:58:22+0200","id":"\\x0001"},{"point":"POINT(11.547133036283018 48.15945941773294)","time":"2014-09-10 06:58:37+0200","id":"\\x0001"},{"point":"POINT(11.544523986408107 48.1580202520987)","time":"2014-09-10 06:58:52+0200","id":"\\x0001"},{"point":"POINT(11.541913157899463 48.156621401719875)","time":"2014-09-10 06:59:07+0200","id":"\\x0001"},{"point":"POINT(11.539193491042212 48.15518473349889)","time":"2014-09-10 06:59:22+0200","id":"\\x0001"},{"point":"POINT(11.537870061505279 48.154492636215736)","time":"2014-09-10 06:59:37+0200","id":"\\x0001"},{"point":"POINT(11.537091818020052 48.15415875046126)","time":"2014-09-10 06:59:52+0200","id":"\\x0001"},{"point":"POINT(11.536790901816994 48.15324523736086)","time":"2014-09-10 07:00:07+0200","id":"\\x0001"},{"point":"POINT(11.536782512341743 48.15269234254464)","time":"2014-09-10 07:00:22+0200","id":"\\x0001"},{"point":"POINT(11.5367825123347 48.15269234253445)","time":"2014-09-10 07:00:37+0200","id":"\\x0001"},{"point":"POINT(11.536781932664688 48.15253742952268)","time":"2014-09-10 07:00:52+0200","id":"\\x0001"},{"point":"POINT(11.536767679186132 48.15216818658186)","time":"2014-09-10 07:01:07+0200","id":"\\x0001"},{"point":"POINT(11.536765548739641 48.15216514582384)","time":"2014-09-10 07:01:22+0200","id":"\\x0001"},{"point":"POINT(11.536765548739641 48.15216514582384)","time":"2014-09-10 07:01:37+0200","id":"\\x0001"},{"point":"POINT(11.536765548739641 48.15216514582384)","time":"2014-09-10 07:01:52+0200","id":"\\x0001"},{"point":"POINT(11.536764208930185 48.15215257571192)","time":"2014-09-10 07:02:07+0200","id":"\\x0001"},{"point":"POINT(11.536717448539342 48.15077090449237)","time":"2014-09-10 07:02:22+0200","id":"\\x0001"},{"point":"POINT(11.536577179945997 48.14905556426255)","time":"2014-09-10 07:02:37+0200","id":"\\x0001"},{"point":"POINT(11.536219651738836 48.14672536176703)","time":"2014-09-10 07:02:52+0200","id":"\\x0001"},{"point":"POINT(11.534835429616662 48.14445337064753)","time":"2014-09-10 07:03:07+0200","id":"\\x0001"},{"point":"POINT(11.534503792853243 48.14198135739431)","time":"2014-09-10 07:03:22+0200","id":"\\x0001"},{"point":"POINT(11.53430400751109 48.1395288033757)","time":"2014-09-10 07:03:37+0200","id":"\\x0001"},{"point":"POINT(11.5344773025581 48.13743976707854)","time":"2014-09-10 07:03:52+0200","id":"\\x0001"},{"point":"POINT(11.534470202357893 48.13730018550079)","time":"2014-09-10 07:04:07+0200","id":"\\x0001"},{"point":"POINT(11.534470202357893 48.13730018550079)","time":"2014-09-10 07:04:22+0200","id":"\\x0001"},{"point":"POINT(11.531785404446792 48.13218461208162)","time":"2014-09-10 07:04:37+0200","id":"\\x0001"},{"point":"POINT(11.529059374060543 48.13058412140918)","time":"2014-09-10 07:04:52+0200","id":"\\x0001"},{"point":"POINT(11.526086100168262 48.12895061004929)","time":"2014-09-10 07:05:07+0200","id":"\\x0001"},{"point":"POINT(11.52328021337131 48.12732106993154)","time":"2014-09-10 07:05:22+0200","id":"\\x0001"},{"point":"POINT(11.521145118689342 48.12545635319235)","time":"2014-09-10 07:05:37+0200","id":"\\x0001"},{"point":"POINT(11.518805036284444 48.124154260618575)","time":"2014-09-10 07:05:52+0200","id":"\\x0001"},{"point":"POINT(11.51406748570058 48.12459192878994)","time":"2014-09-10 07:06:07+0200","id":"\\x0001"},{"point":"POINT(11.508975207499294 48.1252417046577)","time":"2014-09-10 07:06:22+0200","id":"\\x0001"},{"point":"POINT(11.502939020366508 48.12592100387197)","time":"2014-09-10 07:06:37+0200","id":"\\x0001"},{"point":"POINT(11.496993339581742 48.12529215864505)","time":"2014-09-10 07:06:52+0200","id":"\\x0001"},{"point":"POINT(11.491461076432067 48.124118512381735)","time":"2014-09-10 07:07:07+0200","id":"\\x0001"},{"point":"POINT(11.485638038697767 48.123746801395)","time":"2014-09-10 07:07:22+0200","id":"\\x0001"},{"point":"POINT(11.479810083364374 48.12370449280551)","time":"2014-09-10 07:07:37+0200","id":"\\x0001"},{"point":"POINT(11.474748479784534 48.123736702473806)","time":"2014-09-10 07:07:52+0200","id":"\\x0001"},{"point":"POINT(11.470046104061598 48.123849470598095)","time":"2014-09-10 07:08:07+0200","id":"\\x0001"},{"point":"POINT(11.465267017246154 48.124061212453356)","time":"2014-09-10 07:08:22+0200","id":"\\x0001"},{"point":"POINT(11.460509049709275 48.124453904546556)","time":"2014-09-10 07:08:37+0200","id":"\\x0001"},{"point":"POINT(11.455741512458177 48.124867832106766)","time":"2014-09-10 07:08:52+0200","id":"\\x0001"},{"point":"POINT(11.451040963650794 48.12571689514518)","time":"2014-09-10 07:09:07+0200","id":"\\x0001"},{"point":"POINT(11.44745331533991 48.12728964054621)","time":"2014-09-10 07:09:22+0200","id":"\\x0001"},{"point":"POINT(11.44820211189581 48.12848367371619)","time":"2014-09-10 07:09:37+0200","id":"\\x0001"},{"point":"POINT(11.448188695881157 48.12657318984349)","time":"2014-09-10 07:09:52+0200","id":"\\x0001"},{"point":"POINT(11.447812887681284 48.12579914490477)","time":"2014-09-10 07:10:07+0200","id":"\\x0001"},{"point":"POINT(11.447674118953156 48.125656474522486)","time":"2014-09-10 07:10:22+0200","id":"\\x0001"},{"point":"POINT(11.44588547814207 48.125349615749926)","time":"2014-09-10 07:10:37+0200","id":"\\x0001"},{"point":"POINT(11.443396212779412 48.125157071943434)","time":"2014-09-10 07:10:52+0200","id":"\\x0001"},{"point":"POINT(11.440394869142446 48.12541468727304)","time":"2014-09-10 07:11:07+0200","id":"\\x0001"},{"point":"POINT(11.43870044749829 48.126038192952876)","time":"2014-09-10 07:11:22+0200","id":"\\x0001"},{"point":"POINT(11.438684112060958 48.12604659078717)","time":"2014-09-10 07:11:37+0200","id":"\\x0001"},{"point":"POINT(11.438684112060958 48.12604659078717)","time":"2014-09-10 07:11:52+0200","id":"\\x0001"},{"point":"POINT(11.438684112060958 48.12604659078717)","time":"2014-09-10 07:12:07+0200","id":"\\x0001"},{"point":"POINT(11.438684112060958 48.12604659078717)","time":"2014-09-10 07:12:22+0200","id":"\\x0001"},{"point":"POINT(11.438667600462034 48.126054460873725)","time":"2014-09-10 07:12:37+0200","id":"\\x0001"},{"point":"POINT(11.43782808147798 48.12657593323833)","time":"2014-09-10 07:12:52+0200","id":"\\x0001"},{"point":"POINT(11.437720650170544 48.12666131616615)","time":"2014-09-10 07:13:07+0200","id":"\\x0001"},{"point":"POINT(11.437500417040214 48.126714126235505)","time":"2014-09-10 07:13:22+0200","id":"\\x0001"},{"point":"POINT(11.435615169119298 48.127753929402985)","time":"2014-09-10 07:13:37+0200","id":"\\x0001"},{"point":"POINT(11.433758971976749 48.12851044900588)","time":"2014-09-10 07:13:52+0200","id":"\\x0001"}]

**Comment by smattheis** [comment]
Can you please provide the sequence of all commands that use? Including those for starting matcher server, tracker server, tracker monitor, submitting data, etc.

**Comment by biallen** [comment]
> Can you please provide the sequence of all commands that use? Including those for starting matcher server, tracker server, tracker monitor, submitting data, etc.

1.java -jar target/barefoot-0.1.5-matcher-jar-with-dependencies.jar --geojson config/server.properties config/oberbayern.properties
2. java -jar target/barefoot-0.1.5-tracker-jar-with-dependencies.jar config/tracker.properties config/oberbayern.properties
3.node util/monitor/monitor.js 3000 127.0.0.1 1238
4. python util/submit/batch.py --host 127.0.0.1 --port 8888  --file src/test/resources/com/bmwcarit/barefoot/matcher/x0001-015.json

**Comment by smattheis** [comment]
You're submitting a batch job to the matcher server. Submitting data (a stream of data) to the tracker is a completely different use case and, hence, a different command/script, see step 5 here https://github.com/bmwcarit/barefoot#tracker-server

**Comment by biallen** [comment]
> You're submitting a batch job to the matcher server. Submitting data (a stream of data) to the tracker is a completely different use case and, hence, a different command/script, see step 5 here https://github.com/bmwcarit/barefoot#tracker-server

thank you ,  i import oberbayern map data ,but  json coordinate  data is Red Sea of South Africa
,so they does not map ?  how  can create like this json data 
![image](https://user-images.githubusercontent.com/16889394/51671267-82070680-2003-11e9-8e02-08fffeafb74e.png)

**Comment by smattheis** [comment]
I don't get the question: If you need the map of South Africa, why not just stopping the container with the map of Oberbayern and starting a new container to import the map of South Africa?

**Comment by biallen** [comment]
> I don't get the question: If you need the map of South Africa, why not just stopping the container with the map of Oberbayern and starting a new container to import the map of South Africa?

sorry,but  i check  then result timeout.
