### ISSUE TITLE
About simple routing (Dijkstra)

### ISSUE THREAD

**Issue by fly2008begin** [bmwcarit/barefoot#134]
Hello:
Has simple routing (Dijkstra) been developed before? Where can I find the examples?
Thanks a lot!

**Comment by smattheis** [comment]
The library is not optimized for routing and there is no REST-like API for that. Please use the Javadoc for more details on how to use the routing capabilities, see here: https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/topology/Router.java
