### ISSUE TITLE
Unable to find example of online Map maching

### ISSUE THREAD

**Issue by bigbang4u2** [bmwcarit/barefoot#16]
I have stream of latitude and longitude which I want to use for map matching. But I haven't found any good example by which I will be able to achieve this. I am looking for something which will take these latitude and longitude stream and outputs latitude and longitude corresponding to road. Could you you help me with this?

**Comment by smattheis** [comment]
Online map matching is the algorithm's capability to iteratively do map matching without having knowledge over a full sequence of position measurements, but a sequence of position measurements up to the current position. Generation of the stream and all the doing to manage the stream is up to you. Here is the example of how the API looks like: https://github.com/bmwcarit/barefoot/blob/master/MANUAL.md#map-matching-components

In addition to the existing API, I will soon release a REST-like API for the real-time map matching that works as shown here: http://www.bmw-carit.com/blog/announcement-barefoot-release-online-map-matching-with-real-time-visualization-using-nodejs-and-openlayers/

**Comment by bigbang4u2** [comment]
I exactly need what is shown in the video. Could you tell me when would you make this example available. Also could you share what you currently have in video so that I can play with it. Thanks

**Comment by smattheis** [comment]
I actually wanted to publish it some time ago. However, some polishing was necessary and it's ready for release. I can promise it will be published as soon as I have completed our OSS clearance process to have the permission. I try to speed it up and think that it's available within next week at latest, maybe already this week. :)

**Comment by bigbang4u2** [comment]
That would be great, Thanks :)

**Comment by bigbang4u2** [comment]
Hey did you get chance to commit REST API for realtime map matching?

**Comment by smattheis** [comment]
Sorry for the delay. I have the patches ready to commit, but it needs some formal steps before pushing.

**Comment by mmunko** [comment]
Hello, how it is going? Do you have any assumption when you could commit the patches?

**Comment by smattheis** [comment]
It has now been published. Sorry for the delay. Please understand that this is a side project parallel to my PhD project. I hope you can still successfully try the functionality. Let me know about problems, feedback etc. Just create a new issue in case. I'm closing this.
