### ISSUE TITLE
HMM break - no state emissions

### ISSUE THREAD

**Issue by harregui** [bmwcarit/barefoot#17]
Hello! 
As part of my PhD, I'm evaluating the performance of several map matching techniques, under different conditions. I think your implementation of HMM is worth testing, thank you for this great contribution!

However I'm still getting some problems with the online matching, when trying to use the server. I've set up a traffic simulator which is generating coordinate pairs each second and sending them in json format (attached). At this stage output is always already matched, due to the simulation. [input_json_barefoot.txt](https://github.com/bmwcarit/barefoot/files/351033/input_json_barefoot.txt)

Network data was extracted to postgis from https://download.geofabrik.de/europe/andorra-latest.osm.pbf, and created the bfmapways table as stated in your manual. 

I always get the HMM break - no state emissions message, but the network seems complete, and the route follows known links at all times. Any hints? Many thanks in advance.

These are the input data (bfmapways and original GPX file from the simulation output).
![simulation_output_andorra](https://cloud.githubusercontent.com/assets/20325333/16635839/9fa8adfa-43d4-11e6-8bae-3f2da1557067.png)

**Comment by smattheis** [comment]
Yes, I think I found the problem: Your input coordinates are using LatLon while WKT defines 2D point coordinates in X and Y, which is the LonLat format. :)

Thanks for your kind words. If you're interested in some details, as e.g. the implementation of the benchmark shown below [1], please send me an email. (You can find my email address in any source file.) I have also some unpublished improvements of the algorithm that I'm currently evaluating, besides some API implementations [2]. This might be interesting for you.

<img src="http://www.bmw-carit.com/blog/wp-content/uploads/2015/10/benchmark-882x487.png" alt="benchmark-882x487.png">
[1] http://www.bmw-carit.com/blog/barefoot-release-an-open-source-java-library-for-map-matching-with-openstreetmap/
[2] http://www.bmw-carit.com/blog/announcement-barefoot-release-online-map-matching-with-real-time-visualization-using-nodejs-and-openlayers/

**Comment by harregui** [comment]
Thank you very much, you are absolutely right, it works now. I had been struggling with different formatting and writter streams from the simulation output and I failed with such a basic concept.
