### ISSUE TITLE
Barefoot freezes

### ISSUE THREAD

**Issue by larnacoeur** [bmwcarit/barefoot#20]
Hi, I imported Europe extract on my server machine (Xeon E5 1620V3, 96GB RAM, 4TB HDD) and I noticed that Barefoot hangs from time to time for about 25-27 seconds, after that time it continues to work as expected. Can it be related to fact that I set -Xmx and -Xms to 64g and it's just not enough? Screenshot:

![ss](https://cloud.githubusercontent.com/assets/6002981/17295884/d0118348-57fe-11e6-8c2d-c4b460eab8e4.PNG)

**Comment by smattheis** [comment]
Are the processors busy when it freezes? Does it freeze all the time with the same input data?

**Comment by larnacoeur** [comment]
Freezes was most likely caused by mentioned heap settings. I restarted server with -Xmx80g -Xms80g and freezes no longer appears. Server with Europe extract consumes over 70 GB of RAM. Answering your questions: processors was busy and freezes was totally unralated to input data. Maybe it was garbage collection?

**Comment by smattheis** [comment]
An execution of the garbage collection seems to me like the most plausible explanation. Another option could have been a very long path search, but that would have been data dependent. I close this issue as seems to me to be solved.

**Comment by simon-kern** [comment]
You may want to try it with the G1 garbage collector which is designed for large heaps and low latency: http://www.oracle.com/technetwork/systems/g1-intro-jsp-135488.html
