### ISSUE TITLE
Tracker server output format

### ISSUE THREAD

**Issue by smattheis** [bmwcarit/barefoot#21]
Asked by @mmunko:
"I would like to ask, is there a way how to reduce output pushed by websocket only to most probable route, skipping candidates.

Also is there any way how to send som additional information to the tracker, for example, if the vehicle has lights on, etc...., basicly it would be great if I could send set of optional attributes along with the point and in the result, they will appear in the response, e.g. as a separate object, where it will be index of a point in the route and these attributes."

**Comment by smattheis** [comment]
A comfortable way is not implemented yet, but it's easy to accomplish yourself. The tracker server just applies a standard output formatting for sending object states to Barefoot's monitor and, hence, for visualization in the browser with OpenLayers, as illustrated below. (It's basically an example or demonstration of online/real-time map matching.)

<p align="center">
<img src="https://github.com/bmwcarit/barefoot/raw/master/doc-files/com/bmwcarit/barefoot/tracker/tracker-monitor.png" width="550">
</p>

A custom solution may hence replace the monitor and connects to the tracker via ZMQ (http://zeromq.org/) using the publish-subscribe pattern where the cusomt solution subscribes to the trackers publisher endpoint (see parameter `tracker.port`, see https://github.com/bmwcarit/barefoot/wiki#parameters). ZMQ supports various languages, is easy to use and is quite fault-tolerant. For details on ZMQ subscribers, see http://zguide.zeromq.org/page:all#Pub-Sub-Message-Envelopes and the linked Java example http://zguide.zeromq.org/java:psenvsub.

A custom output format of the tracker can then be defined by replacing lines 296-299 in https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/tracker/TrackerServer.java#L296 where some custom defined String object must be passed to the queue, which triggers publication of the update, e.g.:

```java
@Override
public void publish(String id, TrackerServer.State state) {
    try {
        String output = GeometryEngine.geometryToWkt(
                state.inner.estimate().point().geometry(), WktExportFlags.wktExportPoint);
        queue.put(output);
    } catch (Exception e) {
        logger.error("update failed: {}", e.getMessage());
        e.printStackTrace();
    }
}
```

Note that `state.inner`is a `MatcherKState`object and, hence, contains all necessary information. As an example for accessing map matched information, see https://github.com/bmwcarit/barefoot/wiki#building-blocks-and-api or in the Javadoc http://bmwcarit.github.io/barefoot/doc/com/bmwcarit/barefoot/matcher/MatcherKState.html, respectively.

**Comment by mmunko** [comment]
Hello Sebastian thank you for the response, 
I managed to modify the the response pushed by the tracker server to not push candidate routes by modifying the https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/matcher/MatcherKState.java method toMonitorJSON() by commenting lines 190-205.

I would like to ask, Is there any object that stores all points sent in requests? Is it possible to request all given points and get the information supplied in the request? E.g. as a list of points with its time, heading ...

**Comment by smattheis** [comment]
Yes, this should be accessible via this method: http://bmwcarit.github.io/barefoot/doc/0.1.0/com/bmwcarit/barefoot/markov/KState.html#samples--

**Comment by mmunko** [comment]
Thank you, I managed to modify the output of the Barefoot Tracker.
