### ISSUE TITLE
Send position updates of multiple vehicles in one calls to tracker

### ISSUE THREAD

**Issue by mmunko** [bmwcarit/barefoot#24]
Is it possible to send multiple position updates in one call? E.g.:
```
[{"time": 1410324847000,, "point": "POINT(13.98931 49.6765525)", "id": "731"},
 {"time": 1410324847000,, "point": "POINT(13.98931 49.6765525)", "id": "732"}]
```

**Comment by smattheis** [comment]
No, it's not possible but it doesn't have any performance penalty. The rationale is that acutally we have a fleet of vehilces sending position updates individually.
