### ISSUE TITLE
Should direction of vehicle be passed as heading or azimuth.

### ISSUE THREAD

**Issue by mmunko** [bmwcarit/barefoot#25]
In the docs, under the tracker section, there is a list of parameters in the request listed.
One of the params is ```heading```, but in the source code in the https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/matcher/MatcherSample.java, in the lines  91-102 there is:
```
    public MatcherSample(JSONObject json) throws JSONException {
        super(json);
        id = json.getString("id");
        String wkt = json.getString("point");
        point = (Point) GeometryEngine.geometryFromWkt(wkt, WktImportFlags.wktImportDefaults,
                Type.Point);
        if (json.has("azimuth")) {
            azimuth = norm(json.getDouble("azimuth"));
        } else {
            azimuth = Double.NaN;
        }
}
```
Constructor checks for "azimuth" in the json.

**Comment by smattheis** [comment]
The azimuth is a more precise description of the heading. I will correct the documentation.

**Comment by smattheis** [comment]
Fixed.
