### ISSUE TITLE
HMM breaks/no output

### ISSUE THREAD

**Issue by adrianfriday** [bmwcarit/barefoot#31]
Thank you for providing an excellent library with clear instructions.  Great stuff.

I appreciate you must be busy with other things, but if you have ideas of other trouble shooting steps I could try, that'd be appreciated.  I'm not getting any points matched at all (against [greater london OSM data](http://download.geofabrik.de/europe/great-britain/england/greater-london-latest.osm.pbf)), with the following [input data](https://www.dropbox.com/s/7iuyp1pl1m3xuyn/oc-epoch.json?dl=0) (extract below).

The matcher returns:
```
python util/submit/batch.py --host localhost --port 1234  --file src/test/resources/com/bmwcarit/barefoot/matcher/oc-epoch.json 
SUCCESS
{"type":"MultiLineString","coordinates":[]}
```
i.e. SUCCESS, but no points.

My vehicle GPS data is sampled every 3 seconds [in CSV format](https://www.dropbox.com/s/chtaq6zijnqb2oo/oc-99pts.csv?dl=0), so I've had to convert this [to the JSON notation](https://www.dropbox.com/s/7iuyp1pl1m3xuyn/oc-epoch.json?dl=0) expected by barefoot, using the excellent [convertcsv.com](http://www.convertcsv.com/csv-to-json.htm).  Sample:

```
INDEX,TRACK ID,VALID,UTC DATE,UTC TIME,LOCAL DATE,LOCAL TIME,MS,LATITUDE,N/S,LONGITUDE,E/W,ALTITUDE,SPEED,HEADING,G-X,G-Y,G-Z
1,1,FIXED,2016/8/4,6:35:35,2016/8/4,7:35:35,0,51.517646,N,0.125068,W,175.360855,1.177967,129.215155,0.000000,0.000000,0.000000
2,1,FIXED,2016/8/4,6:35:38,2016/8/4,7:35:38,0,51.517613,N,0.125003,W,174.322067,0.760424,166.866982,0.000000,0.000000,0.000000
3,1,FIXED,2016/8/4,6:35:41,2016/8/4,7:35:41,0,51.517575,N,0.124989,W,169.738327,0.245582,182.416140,0.000000,0.000000,0.000000
4,1,FIXED,2016/8/4,6:35:44,2016/8/4,7:35:44,0,51.517533,N,0.124991,W,163.670990,0.177307,177.674236,0.000000,0.000000,0.000000
5,1,FIXED,2016/8/4,6:35:47,2016/8/4,7:35:47,0,51.517524,N,0.124991,W,155.395676,0.071991,340.255272,0.000000,0.000000,0.000000
```

Convert template (assuming date stamps are already imported into Excel time converted to UNIX time, thus ```=(A2-25569)*86400000```:
```
{lb}"id":"\\x0001","point":"POINT(-{f4} {f3})","time":{f2}000{rb}
```

Note, I've had to turn the degrees west into negative degrees East (this looks reasonable when overlaid on the map), and reverse it to LongLat, c.f. [Issue 17](https://github.com/bmwcarit/barefoot/issues/17).

I've also just tried turning the datestamp into epoch time (in ms), c.f. request message format [on the wiki](https://github.com/bmwcarit/barefoot/blob/master/wiki/Home.md).  Links to [Datestamp version](https://www.dropbox.com/s/b9w9pjq87t8hg08/oc.json?dl=0) and [Epoch version](https://www.dropbox.com/s/7iuyp1pl1m3xuyn/oc-epoch.json?dl=0)

```
[
{"id":"\\x0001","point":"POINT(-0.125068 51.517646)","time":1470468935000},
{"id":"\\x0001","point":"POINT(-0.125003 51.517613)","time":1470468938000},
{"id":"\\x0001","point":"POINT(-0.124989 51.517575)","time":1470468941000},
{"id":"\\x0001","point":"POINT(-0.124991 51.517533)","time":1470468944000},
{"id":"\\x0001","point":"POINT(-0.124991 51.517524)","time":1470468947000},
{"id":"\\x0001","point":"POINT(-0.125006 51.517549)","time":1470468950000}
]
```

If you can think of other reasons I might be getting the HMM breaks & no points snapped, I'd really appreciate your thoughts.  If there's further debug information I can enable to help find the problem, I'm happy to do that.

**Comment by smattheis** [comment]
Sorry for the long delay. I rechecked your data and it works (result is attached below), there must be another problem. Can you please send me the output of the matcher when you start it?

<img width="564" alt="oc-geojson" src="https://cloud.githubusercontent.com/assets/7805104/19287469/213e27c2-9002-11e6-8755-8ab99b2fc278.png">

[output.json.txt](https://github.com/bmwcarit/barefoot/files/522903/output.json.txt)

**Comment by adrianfriday** [comment]
Dear Sebastian,

That seems like a quick reply to me - and the output looks good, which is encouraging!

Matcher Server output:

$ java -jar target/barefoot-0.1.0-matcher-jar-with-dependencies.jar --geojson config/server.properties config/oberbayern.properties
2016-10-07 09:49:36,377 INFO  [main] ServerControl: initialize server
2016-10-07 09:49:36,382 INFO  [main] ServerControl: read database properties from file config/oberbayern.properties
2016-10-07 09:49:36,603 INFO  [main] Loader: load map from file /home/ade/Desktop/barefoot/oberbayern.bfmap
2016-10-07 09:49:36,738 INFO  [main] RoadMap: inserting roads ...
2016-10-07 09:49:36,738 INFO  [main] RoadMap: inserted 0 (0) roads and finished
2016-10-07 09:49:36,775 INFO  [main] RoadMap: ~0 megabytes used for road data (estimate)
2016-10-07 09:49:36,813 INFO  [main] RoadMap: index and topology constructing ...
2016-10-07 09:49:36,923 INFO  [main] RoadMap: index and topology constructed
2016-10-07 09:49:36,998 INFO  [main] RoadMap: ~0 megabytes used for spatial index (estimate)
2016-10-07 09:49:36,999 INFO  [main] ServerControl: read tracker properties from file config/server.properties
2016-10-07 09:49:37,116 INFO  [main] MatcherServer: matcher.radius.max=200.0
2016-10-07 09:49:37,117 INFO  [main] MatcherServer: matcher.distance.max=15000.0
2016-10-07 09:49:37,117 INFO  [main] MatcherServer: matcher.lambda=0.0
2016-10-07 09:49:37,117 INFO  [main] MatcherServer: matcher.sigma=4.5
2016-10-07 09:49:37,117 INFO  [main] MatcherServer: matcher.threads=8
2016-10-07 09:49:37,118 INFO  [main] MatcherServer: matcher.interval.min=1000
2016-10-07 09:49:37,118 INFO  [main] MatcherServer: matcher.distance.min=0.0
2016-10-07 09:49:37,118 INFO  [main] AbstractServer: server.port=1234
2016-10-07 09:49:37,118 INFO  [main] AbstractServer: server.timeout.request=15000
2016-10-07 09:49:37,118 INFO  [main] AbstractServer: server.timeout.response=60000
2016-10-07 09:49:37,119 INFO  [main] AbstractServer: server.connections=20
2016-10-07 09:49:37,119 INFO  [main] ServerControl: starting server on port 1234 with map oberbayern
2016-10-07 09:49:37,150 INFO  [main] AbstractServer: listening on port 1234 ...
2016-10-07 09:49:55,090 INFO  [Thread-4] Filter: HMM break - no state emissions
2016-10-07 09:49:55,094 INFO  [Thread-4] Filter: HMM break - no state emissions[…]

Embarrassingly I can now see what happened!   When I first created the VM I didn’t size the disk big enough.  I guess it must’ve truncated ‘oberbayern.bfmap’, so I got (but didn’t notice) inserted 0 roads…

I thought I’d recreated everything, but I guess not!  Removing the .bfmap file caused it to be recreated successfully:

java -jar target/barefoot-0.1.0-matcher-jar-with-dependencies.jar --geojson config/server.properties config/oberbayern.properties
2016-10-11 23:31:14,254 INFO  [main] ServerControl: initialize server
2016-10-11 23:31:14,258 INFO  [main] ServerControl: read database properties from file config/oberbayern.properties
2016-10-11 23:31:14,260 INFO  [main] Loader: load map from database oberbayern
2016-10-11 23:31:14,260 INFO  [main] Loader: open road reader for database oberbayern at localhost:5432
2016-10-11 23:31:14,260 INFO  [main] Loader: database.host=localhost
2016-10-11 23:31:14,260 INFO  [main] Loader: database.port=5432
2016-10-11 23:31:14,260 INFO  [main] Loader: database.name=oberbayern
2016-10-11 23:31:14,261 INFO  [main] Loader: database.table=bfmap_ways
2016-10-11 23:31:14,261 INFO  [main] Loader: database.user=osmuser
2016-10-11 23:31:14,261 INFO  [main] Loader: database.road-types=./map/tools/road-types.json
2016-10-11 23:31:14,400 INFO  [main] PostGISReader: open reader (standard)
2016-10-11 23:31:14,402 INFO  [main] PostGISReader: open reader (parameterized)
2016-10-11 23:31:14,719 INFO  [main] RoadMap: inserting roads ...
2016-10-11 23:31:14,720 INFO  [main] PostGISReader: execute query
2016-10-11 23:31:19,568 INFO  [main] RoadMap: inserted 100000 (188665) roads
2016-10-11 23:31:22,327 INFO  [main] RoadMap: inserted 200000 (376328) roads
2016-10-11 23:31:24,846 INFO  [main] RoadMap: inserted 288176 (530955) roads and finished
2016-10-11 23:31:24,846 INFO  [main] PostGISReader: close reader
2016-10-11 23:31:25,258 INFO  [main] RoadMap: ~98 megabytes used for road data (estimate)
2016-10-11 23:31:28,826 INFO  [main] RoadMap: index and topology constructing ...
2016-10-11 23:31:31,865 INFO  [main] RoadMap: index and topology constructed
2016-10-11 23:31:32,509 INFO  [main] RoadMap: ~42 megabytes used for spatial index (estimate)

and now I get:

$ python util/submit/batch.py --host localhost --port 1234  --file src/test/resources/com/bmwcarit/barefoot/matcher/oc-epoch.json
SUCCESS
{"type":"MultiLineString","coordinates":[[[-0.12477462706179297,51.51737544621245],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12475458402218746,51.51738390597918]],[[-0.12475458402218746,51.51738390597918],[-0.12466943475208712,51.51741984571229]],[[-0.12466943475208712,51.51741984571229],[-0.1246359,51.517434],[-0.12455538353857658,51.51746796135099]],[[-0.12455538353857658,51.51746796135099],[-0.12452615681586203,51.51748028897766]],[[-0.12452615681586203,51.51748028897766],[-0.12452615681586203,51.51748028897766]],[[-0.12452615681586203,51.51748028897766],[-0.12447651752875137,51.51750122644884]],[[-0.12447651752875137,51.51750122644884],[-0.12440634832850375,51.51753082321149]],[[-0.12440634832850375,51.51753082321149],[-0.12429911105001248,51.517576054813865]],[[-0.12429911105001248,51.517576054813865],[-0.1242798,51.5175842],[-0.1242041876655367,51.517616108790534]],[[-0.1242041876655367,51.517616108790534],[-0.1240862,51.5176659],[-0.12404687092261887,51.517683379630846]],[[-0.12404687092261887,51.517683379630846],[-0.123926,51.5177371],[-0.12384920947450416,51.51777124980292]],[[-0.12384920947450416,51.51777124980292],[-0.1237605,51.5178107],[-0.1236955,51.5178392],[-0.12362704609096918,51.51786798393405]],[[-0.12362704609096918,51.51786798393405],[-0.1233983686032912,51.51796413914141]],[[-0.1233983686032912,51.51796413914141],[-0.1231692,51.5180605],[-0.12315508648002095,51.51806674014812]],[[-0.12315508648002095,51.51806674014812],[-0.1229149013545085,51.51817293501544]],[[-0.1229149013545085,51.51817293501544],[-0.1229091,51.5181755],[-0.1228674,51.5181939],[-0.12283,51.5182104],[-0.1227821,51.5182316],[-0.12268878533068543,51.518271401631004]],[[-0.12268878533068543,51.518271401631004],[-0.1225097530476952,51.51834776410788]],[[-0.1225097530476952,51.51834776410788],[-0.1224044,51.5183927],[-0.1223535,51.5184144],[-0.12232679166168192,51.518425787637526]],[[-0.12232679166168192,51.518425787637526],[-0.1222951,51.5184393],[-0.12217912130138762,51.51848986266372]],[[-0.12217912130138762,51.51848986266372],[-0.1221038,51.5185227],[-0.12206513095962804,51.51853957476178]],[[-0.12206513095962804,51.51853957476178],[-0.12188548424745538,51.518617970362754]],[[-0.12188548424745538,51.518617970362754],[-0.1217949,51.5186575],[-0.12174310725467882,51.518681833508225]],[[-0.12174310725467882,51.518681833508225],[-0.12171221328130312,51.51869634823503]],[[-0.12171221328130312,51.51869634823503],[-0.12160555416347067,51.51874645910315]],[[-0.12160555416347067,51.51874645910315],[-0.12144007507247062,51.518824204515774]],[[-0.12144007507247062,51.518824204515774],[-0.1213807,51.5188521],[-0.12132915407687585,51.51887365799025]],[[-0.12132915407687585,51.51887365799025],[-0.12130349352250577,51.51888438995741]],[[-0.12130349352250577,51.51888438995741],[-0.1212633,51.5189012],[-0.12125818601507514,51.51890318877569]],[[-0.12125818601507514,51.51890318877569],[-0.1211607,51.5189411],[-0.12111687925892986,51.51896748575755]],[[-0.12111687925892986,51.51896748575755],[-0.1209727,51.5190543],[-0.1209344,51.5190256],[-0.1209069,51.5189861],[-0.1208642,51.5189016],[-0.12085897374667977,51.51888969106433]],[[-0.12085897374667977,51.51888969106433],[-0.12079780641279718,51.518750310075056]],[[-0.12079780641279718,51.518750310075056],[-0.12071559093007297,51.518562965622166]],[[-0.12071559093007297,51.518562965622166],[-0.12065550833999932,51.51842605438804]],[[-0.12065550833999932,51.51842605438804],[-0.12063193803843665,51.5183723441019]],[[-0.12063193803843665,51.5183723441019],[-0.12062939855090424,51.51836655729486]],[[-0.12062939855090424,51.51836655729486],[-0.12061943087226808,51.51834384362933]],[[-0.12061943087226808,51.51834384362933],[-0.12061001090787578,51.518322378036]],[[-0.12061001090787578,51.518322378036],[-0.12060879635204415,51.51831961038478]],[[-0.12060879635204415,51.51831961038478],[-0.12060879635204415,51.51831961038478]],[[-0.12060879635204415,51.51831961038478],[-0.1205951,51.5182884],[-0.12058552209437444,51.51824944844039]],[[-0.12058552209437444,51.51824944844039],[-0.12057379795296828,51.51820176844747]],[[-0.12057379795296828,51.51820176844747],[-0.12056296505364376,51.51815771288729]],[[-0.12056296505364376,51.51815771288729],[-0.1205532,51.518118],[-0.12054326226911748,51.518091696750666]],[[-0.12054326226911748,51.518091696750666],[-0.1205297,51.5180558],[-0.12049764760402246,51.51798589253436]],[[-0.12049764760402246,51.51798589253436],[-0.12046796862731994,51.51792116138489]],[[-0.12046796862731994,51.51792116138489],[-0.12043126744166624,51.51784111422461]],[[-0.12043126744166624,51.51784111422461],[-0.1203999,51.5177727],[-0.12039629773125089,51.51776489050502]],[[-0.12039629773125089,51.51776489050502],[-0.1203868,51.5177443],[-0.12035703702705534,51.51767938310033]],[[-0.12035703702705534,51.51767938310033],[-0.1203338,51.5176287],[-0.12031071124226231,51.51757853699329]],[[-0.12031071124226231,51.51757853699329],[-0.1202834,51.5175192],[-0.12022854701838664,51.51742863662415]],[[-0.12022854701838664,51.51742863662415],[-0.12016040584234786,51.51731613363408]],[[-0.12016040584234786,51.51731613363408],[-0.12003447862815199,51.51710822270795]],[[-0.12003447862815199,51.51710822270795],[-0.1200126,51.5170721],[-0.11992912840298547,51.5169515544382]],[[-0.11992912840298547,51.5169515544382],[-0.1198595,51.516851],[-0.1197361,51.516667],[-0.1197068,51.5166173],[-0.119578,51.5164474],[-0.1195262,51.5163776],[-0.11947439902947901,51.51629292394176]],[[-0.11947439902947901,51.51629292394176],[-0.1194575,51.5162653],[-0.1190897,51.5157155],[-0.11905763307885624,51.515665039687164]],[[-0.11905763307885624,51.515665039687164],[-0.118945,51.5154878],[-0.11892023626285421,51.51545238695407]],[[-0.11892023626285421,51.51545238695407],[-0.11888908608280067,51.51540784097648]],[[-0.11888908608280067,51.51540784097648],[-0.11879593611954639,51.5152746323106]],[[-0.11879593611954639,51.5152746323106],[-0.11871792381970855,51.51516307053175]],[[-0.11871792381970855,51.51516307053175],[-0.11862104475623929,51.51502452743366]],[[-0.11862104475623929,51.51502452743366],[-0.1185311,51.5148959],[-0.11820536576180211,51.51441463016247]],[[-0.11820536576180211,51.51441463016247],[-0.1181623,51.514351],[-0.1180223,51.5141393],[-0.1179162,51.5139901],[-0.1178172746536004,51.51385101581616]],[[-0.1178172746536004,51.51385101581616],[-0.11776347458491097,51.51377537516694]],[[-0.11776347458491097,51.51377537516694],[-0.11774739387022916,51.513752766300215]],[[-0.11774739387022916,51.513752766300215],[-0.11768687507947113,51.513667678985435]],[[-0.11768687507947113,51.513667678985435],[-0.11765816134133385,51.513627308346116]],[[-0.11765816134133385,51.513627308346116],[-0.1176477,51.5136126],[-0.11760159865050179,51.513521520318015]],[[-0.11760159865050179,51.513521520318015],[-0.1175738,51.5134666],[-0.1175508,51.5134206],[-0.1175232,51.5133795],[-0.1174684,51.513325],[-0.1174248,51.513308],[-0.117351,51.5132872],[-0.1172695,51.5132742],[-0.1171477,51.5132632],[-0.11703682115784589,51.51326958720101]],[[-0.11703682115784589,51.51326958720101],[-0.1169498,51.5132746],[-0.11665728750355431,51.51329193991779]],[[-0.11665728750355431,51.51329193991779],[-0.1166529,51.5132922],[-0.1163592,51.5132975],[-0.11617997358410086,51.51329320042112]],[[-0.11617997358410086,51.51329320042112],[-0.1161216,51.5132918],[-0.1160301,51.5132812],[-0.11570602191998948,51.51322805773623]],[[-0.11570602191998948,51.51322805773623],[-0.1156703,51.5132222],[-0.11529021178731605,51.513100866654376]],[[-0.11529021178731605,51.513100866654376],[-0.1150867,51.5130359],[-0.11502854606416962,51.513019970693755]],[[-0.11502854606416962,51.513019970693755],[-0.1149644,51.5130024],[-0.1148936,51.5129752],[-0.11486789361190378,51.51294930082375]],[[-0.11486789361190378,51.51294930082375],[-0.1148536,51.5129349],[-0.1148274,51.5128816],[-0.1148341,51.5128497],[-0.1148428073133336,51.51283042651757]],[[-0.1148428073133336,51.51283042651757],[-0.11484689160228947,51.51282138601109]],[[-0.11484689160228947,51.51282138601109],[-0.1148519,51.5128103],[-0.1149052,51.5127382],[-0.11494416570041768,51.512715257884054]],[[-0.11494416570041768,51.512715257884054],[-0.115046,51.5126553],[-0.11505803911871851,51.51265183407022]],[[-0.11505803911871851,51.51265183407022],[-0.11520283503782597,51.51261014878059]],[[-0.11520283503782597,51.51261014878059],[-0.11539642041534613,51.51255441709779]],[[-0.11539642041534613,51.51255441709779],[-0.1154135,51.5125495],[-0.11565346018936967,51.51247170418637]],[[-0.11565346018936967,51.51247170418637],[-0.1157494,51.5124406],[-0.115989,51.5123508],[-0.11603926243931922,51.512330475640724]],[[-0.11603926243931922,51.512330475640724],[-0.11647496055496612,51.51215429301279]],[[-0.11647496055496612,51.51215429301279],[-0.1164972,51.5121453],[-0.11685318798269605,51.51202743373663]],[[-0.11685318798269605,51.51202743373663],[-0.1168548,51.5120269],[-0.11700551891672897,51.51198887374293]],[[-0.11700551891672897,51.51198887374293],[-0.11702433131136451,51.51198412737339]],[[-0.11702433131136451,51.51198412737339],[-0.11702433131136451,51.51198412737339]],[[-0.11702433131136451,51.51198412737339],[-0.11702433131136451,51.51198412737339]],[[-0.11702433131136451,51.51198412737339],[-0.11702433131136451,51.51198412737339]],[[-0.11702433131136451,51.51198412737339],[-0.11702433131136451,51.51198412737339]],[[-0.11702433131136451,51.51198412737339],[-0.1170831,51.5119693],[-0.11712783628394825,51.51195890769012]]]}


[cid:DB16C9E7-DFAE-41F1-BB48-CD9A9CF8BE5B@lan]

i.e. it works!  Sorry to have bothered you, but thank you so much for helping find the problem.

Best,

Adrian.

**Comment by smattheis** [comment]
You're very welcome. I'm closing this issue. Feel free to create a new issue if there's another problem or question.
