### ISSUE TITLE
Can not start test map server and the Tracker server in OSGeo-Live 10

### ISSUE THREAD

**Issue by wuyujack** [bmwcarit/barefoot#38]
Hello, I had build the barefoot on OSGeo-Live 10. I have try so much times to run the test map server and the Tracker server, however they could not start. Here is the  error informations that the Tracker control can not start: 

**user@user-VirtualBox:~/barefoot$ java -jar target/barefoot-0.1.0-tracker-jar-with-dependencies.jar config/tracker.properties config/oberbayern.properties
2017-01-17 13:17:07,913 INFO  [main] TrackerControl: initialize server
2017-01-17 13:17:07,922 INFO  [main] TrackerControl: read database properties from file config/oberbayern.properties
2017-01-17 13:17:07,940 INFO  [main] Loader: load map from database oberbayern
2017-01-17 13:17:07,942 INFO  [main] Loader: open road reader for database oberbayern at localhost:5432
2017-01-17 13:17:07,945 INFO  [main] Loader: database.host=localhost
2017-01-17 13:17:07,956 INFO  [main] Loader: database.port=5432
2017-01-17 13:17:07,957 INFO  [main] Loader: database.name=oberbayern
2017-01-17 13:17:07,957 INFO  [main] Loader: database.table=bfmap_ways
2017-01-17 13:17:07,958 INFO  [main] Loader: database.user=osmuser
2017-01-17 13:17:07,958 INFO  [main] Loader: database.road-types=./map/tools/road-types.json
2017-01-17 13:17:08,073 INFO  [main] PostGISReader: open reader (standard)
2017-01-17 13:17:08,081 INFO  [main] PostGISReader: open reader (parameterized)
2017-01-17 13:17:08,328 ERROR [main] TrackerControl: Opening PostgreSQL connection failed: FATAL: role "osmuser" does not exist
2017-01-17 13:17:08,337 INFO  [Thread-0] TrackerControl: stopping server
2017-01-17 13:17:08,338 ERROR [Thread-0] TrackerControl: stopping server failed, not yet started**

**Comment by wuyujack** [comment]
Here is the error information that **mvn test**  build failure
**Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.910 s
[INFO] Finished at: 2017-01-17T13:14:11+08:00
[INFO] Final Memory: 16M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project barefoot: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/user/barefoot && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/user/barefoot/target/surefire/surefirebooter6015454021290868925.jar /home/user/barefoot/target/surefire/surefire2274270870239432392tmp /home/user/barefoot/target/surefire/surefire_02135993547783545079tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException**

**Comment by jongiddy** [comment]
Do you have a PostgreSQL database setup on the local host with these credentials?
```
database.host=localhost
database.port=5432
database.name=oberbayern
database.table=bfmap_ways
database.user=osmuser
```
If your database has different credentials, or is on a different host, you need to change these settings.

**Comment by smattheis** [comment]
Either your database setup failed/crashed or something else (maybe due to insufficient disk memory?) or you imported the data, i.e. bash `/mnt/map/osm/import.sh`, with some parameters that differ from your database settings as @jongiddy said. To setup the database and import data with default settings, just run `bash /mnt/map/osm/import.sh`without any parameter set. Only then you can use the default database properties file.

**Comment by wuyujack** [comment]
@jongiddy @smattheis I have followed the guide of building the Test map server, and didn't change any parameter. I have watched the file **oberbayern.properties** on **/barefoot/config**. Actually I don't have database.user named **osmuser**, is it the default settings?

**Comment by wuyujack** [comment]
@jongiddy @smattheis and the other error is that when I run the **sudo docker run -it -p 5432:5432 --name="barefoot-oberbayern" -v ${PWD}/map/:/mnt/map barefoot-map**, it returns that error. I googled it and changed my docker-compose ports section from 5432:5432 to just 5432 and let docker choose the port automatically, and then it succeed. Is it the factor that lead to the error of starting the server?

**Comment by smattheis** [comment]
"[...] and then it succeed." - Does that mean it's working now?
"Actually I don't have database.user named osmuser, is it the default settings?" - Yes, that's the default. If you didn't change the user when setting up the database with `bash /mnt/map/osm/import.sh`with something like `bash /mnt/map/osm/import.sh map.osm.pbf map myuser mypass road-types.json slim`, you also shouldn't change the user name in the database properties file.
"Is it the factor that lead to the error of starting the server?" - According to your error message, where the tracker server could connect to the database, but couldn't login because the user didn't exist, I would guess that this is/was not the original error.

**Comment by wuyujack** [comment]
@smattheis I uninstall the barefoot and try again, maybe I can fix it, thank you and @jongiddy so much!
however, there are other question: when I build Docker image **sudo docker build -t barefoot-map ./map**, in the step 6 the following information (word color is red) appears serval times:

**debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
**

Finally, step 6 returns **BUILD SUCCESSFUL**. So it means that infomation can be ignored?

**Comment by smattheis** [comment]
You're welcome. The warnings are probably due to some dialogs appearing in the installation of some libraries. Although we should never ignore warnings, I think for now it's most important that it works. :)

**Comment by wuyujack** [comment]
@smattheis "[...] and then it succedd."   the following information returns when changed my docker-compose ports section from 5432:5432 to just 5432 and let docker choose the port automatically.

**user@user-VirtualBox:~/barefoot$ sudo docker run -it -p 5432 --name="barefoot-oberbayern" -v ${PWD}/map/:/mnt/map barefoot-map
[sudo] password for user: 
 * Starting PostgreSQL 9.3 database server                       [ OK ]**

**Comment by smattheis** [comment]
Actually, this shouldn't be a problem. Is it possible that you're running a PostgreSQL database already on your system? That would explain that it only works if you let Docker choose a random port AND the reason that your (already installed) database doesn't know the user. On Linux, you could check that with `netstat`, e.g. `netstat -lpn | grep 5432". Maybe some other process blocks that port or you have a container that blocks it. (`docker ps -a` will tell you, if you have some weird container blocking that port.)

**Comment by wuyujack** [comment]
@smattheis yes I am already running a PostgreSQL database on my system because I am using the OSGeo-Live[https://live.osgeo.org/en/index.html](url). So I have already installed the PostgreSQL, PostGIS, Osmosis, Python and other opensource GIS tools as the prerequisite.

**Comment by smattheis** [comment]
Okay, then you could map the database port to 5433 (`-p 5433:5432`) and also configure it in the properties file, i.e. `database.port=5433`.

**Comment by wuyujack** [comment]
@smattheis thank you so much! I use the **sudo docker ps -a** and find that the random port given by the linux is 32469, and then I configure it, and the test run successfully : )

**Comment by wuyujack** [comment]
@smattheis Thank you so much! I use the **sudo docker ps -a** and find the random port given by the Linux and then configure it in the properties. The test finally run but there still an error return:
**
2017-01-17 18:51:24,704 INFO  [main] Loader: load map from file /home/user/barefoot/oberbayern.bfmap
2017-01-17 18:51:28,198 INFO  [main] RoadMap: inserting roads ...
2017-01-17 18:51:29,853 INFO  [main] RoadMap: inserted 100000 (192553) roads
2017-01-17 18:51:31,211 INFO  [main] RoadMap: inserted 200000 (387647) roads
2017-01-17 18:51:32,717 INFO  [main] RoadMap: inserted 300000 (582543) roads
2017-01-17 18:51:34,089 INFO  [main] RoadMap: inserted 400000 (774674) roads
2017-01-17 18:51:39,983 INFO  [main] RoadMap: inserted 500000 (967438) roads
2017-01-17 18:51:41,158 INFO  [main] RoadMap: inserted 588717 (1135199) roads and finished
2017-01-17 18:51:46,376 INFO  [main] RoadMap: ~203 megabytes used for road data (estimate)
2017-01-17 18:51:50,563 INFO  [main] RoadMap: index and topology constructing ...
2017-01-17 18:51:57,546 DEBUG [Thread-18] TrackerServer: delete object \x0001
2017-01-17 18:52:58,044 INFO  [main] RoadMap: index and topology constructed
2017-01-17 18:53:03,243 INFO  [main] RoadMap: ~88 megabytes used for spatial index (estimate)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 214.456 sec <<< FAILURE! - in com.bmwcarit.barefoot.road.BfmapReaderTest
testBfmapReader(com.bmwcarit.barefoot.road.BfmapReaderTest)  Time elapsed: 214.446 sec  <<< ERROR!
java.lang.OutOfMemoryError: Java heap space
	at sun.reflect.GeneratedSerializationConstructorAccessor2.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1006)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1792)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.bmwcarit.barefoot.road.BfmapReader.next(BfmapReader.java:93)
	at com.bmwcarit.barefoot.road.BfmapReaderTest.testBfmapReader(BfmapReaderTest.java:56)


Results :

Failed tests: 
  TrackerServerTest.testTrackerServer:152->sendSample:90 expected:<[SUCCESS]> but was:<[TIMEOUT]>

Tests in error: 
  BfmapReaderTest.testBfmapReader:56 » OutOfMemory Java heap space

Tests run: 75, Failures: 1, Errors: 1, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:04 min
[INFO] Finished at: 2017-01-17T18:55:00+08:00
[INFO] Final Memory: 16M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project barefoot: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/barefoot/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException**

**Comment by wuyujack** [comment]
@smattheis Thank you so much! I fixed the problem and run the tracker successfully
