### ISSUE TITLE
BareFoot with H2GIS

### ISSUE THREAD

**Issue by nicolas-f** [bmwcarit/barefoot#4]
Hi,

H2GIS is a 100% java standalone spatial database able to [import openstreetmap data][1] . Can you give us some guidelines in order to link through jdbc barefoot to a localhost h2gis database then doing map matching ?

Thanks
[1]:http://www.h2gis.org/docs/dev/OSMRead/

**Comment by smattheis** [comment]
Have a look to the PostGISReader (https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/road/PostGISReader.java) and implement your own Reader variant, that should implement the RoadReader interface. If you're using the stand-alone server you also need to replace the map loading in ServerControl (https://github.com/bmwcarit/barefoot/blob/master/src/main/java/com/bmwcarit/barefoot/matcher/ServerControl.java). That should do it.
Please feel free to branch it and make a pull-request, or submit your code in any other way!

**Comment by nicolas-f** [comment]
Nice, thanks for your help !

Maybe I will write a gpl standalone project with barefoot and embedded h2gis for a single jar deployment solution.
