### ISSUE TITLE
Matcher Server SUCCESS but return empty coordinates list

### ISSUE THREAD

**Issue by wuyujack** [bmwcarit/barefoot#46]
I am using the dataset from Hengfeng Li project [people.eng.unimelb.edu.au/henli/projects/map-matching](url) and the dataset is here [http://people.eng.unimelb.edu.au/henli/projects/map-matching/gps_track.txt](url). I start the Matcher Server and run the code
`user@user-VirtualBox:~/barefoot$ python util/submit/batch.py --host localhost --port 1235 --file test.json
`
where the contents of **test.json** are
`[
    {"id":"1","time":1381601722,"point":"POINT(144.947925 -37.798779)"},
    {"id":"2","time":1381601723,"point":"POINT(144.947900 -37.798449)"},
    {"id":"3","time":1381601724,"point":"POINT(144.947885 -37.798749)"}
]`

The Matcher Server is successfully set up but return empty coordinates list. 
`user@user-VirtualBox:~/barefoot$ python util/submit/batch.py --host localhost --port 1235 --file test.json
SUCCESS
{"coordinates":[],"type":"MultiLineString"}
`
Are there something wrong with my setup? I use the `melbourne.osm.pbf` file from [https://mapzen.com/data/metro-extracts/metro/melbourne_australia/](url) and the default `road-types.json`

**Comment by smattheis** [comment]
The time must be provided in milliseconds, which means that you need to add "000" to each of the timestamps. I'm not sure if that solves the problem, but that's what you could or should try first.

**Comment by smattheis** [comment]
Does that solve the problem?

**Comment by wuyujack** [comment]
@smattheis Thank you so much! I left my office and now I figure it out!

**Comment by wuyujack** [comment]
@smattheis I have run for 2500 GPS points, however the return result is too large and the length of linux terminal is limited, so I want to store the result in a JSON file. Do I need to modify the code of barefoot?

**Comment by wuyujack** [comment]
@smattheis I found the solution to overcome it :), it just a linux skill, thank you so much!
