### ISSUE TITLE
Negative coordinates

### ISSUE THREAD

**Issue by larnacoeur** [bmwcarit/barefoot#48]
Hi,

recently I came across a very strange Barefoot response.

![bfnegcoord](https://cloud.githubusercontent.com/assets/6002981/23161983/84338f88-f82c-11e6-9f68-8d77c9ebf474.PNG)

Black polyline at the left represents position samples and colored polyline is the matching response.
Route started at: 48,53449 -2,76065 and ended at: 48,47902 -2,62564. I noticed that route looks kind of mirrored, as if negative coordinates were reversed. I debugged whole communication from my client app to Barefoot and it looks like everything is passed in the right way, so I'm wondering if maybe it's a bug in the Barefoot itself? Have you ever tested it with negative coordinates?

**Comment by larnacoeur** [comment]
Turned out it was a problem with response parsing. Sorry for bothering you.

**Comment by smattheis** [comment]
No problem.
