### ISSUE TITLE
confusing map matching results & errors

### ISSUE THREAD

**Issue by raethlo** [bmwcarit/barefoot#5]
Hello, first of all thanks for an amazing work on the barefoot library. I'd like to use barefoot in my masters thesis as a map matching component, the aim of my research is to augment road speed information for road segments with contextual information such as weather or time context to improve the accuracy traffic dynamics prediction. To do so I have to extract speed from raw GPS traces and map it to underlying street graph (that is where barefoot would come really handy).

I have followed the manual, set up the docker container as described and imported a reasonable chunk of osm data for my needs without any major problem, but when I attempt to run the "hello-world" map-matching example, the GPS trace is not mapped correctly. For example consider this raw gps trace:

![raw](https://dl.dropboxusercontent.com/u/55261792/raw.png)

Which gets mapped as:

![bad](https://dl.dropboxusercontent.com/u/55261792/bad.png)

I used the example provided, and did a null-check on transition, because it was raising NullPointer
```java
// Iterative map matching of sample batch (offline) or sample stream (online)
        for (MatcherSample sample : samples) {
            Set<MatcherCandidate> vector = matcher.execute(state.vector(), state.sample(),
                    sample);
            state.update(vector, sample);

            //  Online map matching result
            MatcherCandidate estimate = state.estimate(); // most likely position estimate

            if(estimate != null) {
                long id = estimate.point().edge().id(); // road id
                Point position = estimate.point().geometry(); // position

                System.out.println(position.getY() + ", " + position.getX() + ", " + sample.time() );

                MatcherTransition transition = estimate.transition();
                if(transition != null) {
                    Route route = transition.route(); // route to position
                }
            } else {
                System.out.println("no estimate");
            }
        }
```
and I instantiate the MatcherSamples like so
```java
Point point = new Point(lng, lat);
MatcherSample ms = new MatcherSample(time.toString(), time, point);
```
Additionally,  I have found out, that multiple successive points often get mapped to an identical resulting position and in output i get `Filter: HMM break - no state transitions`. I get the impression as if it the road graph was incorrect or maybe my MatcherSamples lacked the definition of a correct spatial reference and thus were not matched correctly. Is there something I might have overlooked that might have caused this issue?

Thanks

**Comment by smattheis** [comment]
You're using the online map matching results. If you don't need real-time map matching, just use the Matcher.mmatch() method which does the full map matching and outputs the "final" result. If you really need online map matching, you're doing it right but could optimize it. (Let me know, then I can explain it.) I would at least give the mmatch method a try and see the result.

Hint: You can use MatcherKState.toGeoJSON() to output the result in GeoJSON and see the result on geojson.io. For that purpose, just replace the KState by MatcherKState in your code. (I need to update the API description in the readme. :) )

**Comment by raethlo** [comment]
Thanks for such a quick response. ```Matcher.mmatch()``` still does emit ```Filter: HMM break - no state transitions``` few times and the resulting match still contains multiple identical successive points. This is the geojson response from the map matching 

https://gist.github.com/raethlo/bb374ac8a38882eb759c35cb870e0a6d?short_path=4f84da5

**Comment by smattheis** [comment]
An HMM break with "no state transition" shows that something is wrong with the road map. Is it possible that you send me a sample track (via email if you like)? I can test the import without sample track, but to fully check what's wrong it may help.

**Comment by raethlo** [comment]
I thought that might be the case, sure [this is the short trace](https://gist.github.com/raethlo/c97c1eabc653e8cc283d63c0255b2044) I was running the matching with. As for the map data I have imported .pbf for Vienna,Austria from https://mapzen.com/data/metro-extracts/ (I have tried importing the whole [country-sized osm export](http://download.geofabrik.de/europe/austria.html) , but the issue persisted).

Thanks a lot for help

**Comment by smattheis** [comment]
Okay, I think I found the problem: I guess you use the timestamps in seconds epoch time, however, the library expects milliseconds epoch time. Since the matcher uses the time intervals to calculate transition probabilities it experiences distances too far for the low time intervals and detects HMM breaks.

My output with corrected timestamps using the stand-alone matcher is this:
![vienna-trace](https://cloud.githubusercontent.com/assets/7805104/14438783/1b6f1c62-0028-11e6-873f-1a5ce62dedf2.png)

**Comment by raethlo** [comment]
:see_no_evil: I can't understand how I could not have noticed that, I have literally spent days on trying to figure out what is wrong with the street graph. Thanks a lot for help, I owe you a :beer:

**Comment by smattheis** [comment]
:+1: Feel free to come to Munich for that purpose and to present your thesis. :)
