### ISSUE TITLE
Question: output format of online Tracker Server

### ISSUE THREAD

**Issue by wuyujack** [bmwcarit/barefoot#53]
Thank you so much for your great contribution. As the Wiki said, After the success of Tracker server, the track can be visualized on http://localhost:3000. It's very easy for us to know whether the map matching result is right by visualizing in the map. However, if the time interval becomes bigger, for example each 45s to get a GPS point, I can just know the map matching of each point, not the whole trajectory, because I can just see the red pot in the map, and I have no idea which route the point has gone through, and the respond time for the online map matching algorithm to match a GPS point in each 45s.  So I am just curious about whether I can get the whole output result in a file, include respond time, the online map matching result and the routing between each two results, for example in a  JSON file.

**Comment by smattheis** [comment]
(1) The tracker server (https://github.com/bmwcarit/barefoot#tracker-server-quick-start) does online map matching which matches the full route iteratively. You visualize the result in the monitor, i.e. visualization on http://localhost:3000, where you see, by default, only the most recent matched position as a red point and also the full route if you hover the mouse over the red point (and candidates, which looks like a little tree, in green and some level of transparency according to the probability of the respective candidate).
(2) The matcher server (https://github.com/bmwcarit/barefoot#matcher-server-quick-start) does offline map matching which matches the full route in a single step (batch job) and returns the matched result in a JSON file. This sounds actually more suitable to what you're looking for.
(3) If you want online map matching results iteratively in JSON. You must connect to the ZeroMQ interface of the tracker, as shown in the scheme here: https://github.com/bmwcarit/barefoot/wiki#tracker-server

**Comment by wuyujack** [comment]
Thank you so much , I hover the mouse over the red point and nothing happen. When I click the red point and see the candidates in green, however I still can not see the route as the gif showing in the  https://github.com/bmwcarit/barefoot/wiki#tracker-server. Had I mixed up something?
![image](https://cloud.githubusercontent.com/assets/10961996/24601285/da87b82c-188a-11e7-8f5d-ca459db7bed7.png)

**Comment by smattheis** [comment]
Okay, few questions for diagnosis:

1.) Does the image show the output of matching from the same object? If yes, make sure that the samples, that you send to the tracker, have the same id if samples refer to the same object. If this is the problem, you can discard question 2.

2.) Do you see something like "HMM break" in the console output of the tracker server? If yes, can you please provide your tracker.properties file?

**Comment by wuyujack** [comment]
1) Yes, the image show the output of matching from the same object because the time interval of the GPS point is 1Hz, so we can see so many matching result in the image. I may need to confirm the id, do you mean that I need to change the id, for example ` "id"=1`for all the GPS data in the input, so that the route can generate automatically?
2)I didn't "HMM break" in the console output of the tracker server. Based on the tracker server(online) matching output, the matcher server(offline) output and my groundtruth data, I think the map matching algorithm is all right, although I can just see the point but not include the route of the map matching output, but I can see the whole route by using the offline server. And if the online and offline server use the same algorithm, I think the problem is just that I can not see the route dymatically in http://localhost:3000.

**Comment by wuyujack** [comment]
I can change the id and I can see the whole route of the same object. Thank you so much~ @smattheis And I had another question about the online map matching respond time. Because I can see the whole respond time in the console when I use the matcher server, and then I can calculate the average respond time of one GPS point. However, though the offline and online algorithm have some similarities in your system, I think the online algorithm's respond time can not be equal to the offline, for each point. Do you think that I can use the offline algorithm's average respond time to represent the online algorithm's average respond time for a GPS point?

**Comment by smattheis** [comment]
Yes, that should be basically the same, in average. The reason is that online map matching processes GPS points iteratively while the offline map matching performs the same iterations at once.
