### ISSUE TITLE
Unwanted road types when using import.sh

### ISSUE THREAD

**Issue by GeoCrunch** [bmwcarit/barefoot#58]
Hi

I have been using the import script and the default road-types.json file to produce my map server, but my matching results are including roads that should be excluded by the import script(s). In particular, when I import the geofabrik extract for all Australia using the script and match my GPS traces I get "construction", "footway", "proposed", "rest-area" and "track" amongst the results (including the imputed routes).

For instance, there is a section of highway being constructed to bypass the towns of Nambucca Heads and Macksville [here](http://www.openstreetmap.org/#map=13/-30.6841/152.9768). I have a small number of observations that are matched to where the old and proposed roads meet, which is sensical. But when a vehicle has passed from south of the in construction bypass to the north without pinging, the algorithm logically expects they have taken the direct route, and so this segment is attributed to a great many vehicle journeys (parts of my data are relatively low resolution). 

But the road should be available for matching at all. The "highway" tag clearly says "construction" and is not included in road-types.json. I tried adding "construction" (and the others) to road-types with arbitrarily priorities (99) and zero speed to try and dissuade any matches, but to no avail.

This isn't a major problem, since the majority of my data is of sufficient resolution that the actual route is matched most of the time (and I am mainly concerned about the underlying roads and can safely ignore ones that don't exist yet), but it is bemusing.

Thank you once again

**Comment by smattheis** [comment]
Is it possible that you have imported an older dataset before where the road wasn't under construction? If so, it could be that you have an old version of the bfmap file that is used by the matcher instead of the new map version from the database. If you just delete that file, the matcher will read the new data from the database and the road should be ignored if it's under construction.

**Comment by GeoCrunch** [comment]
Hi again, sorry for the delay in responding.

The road is brand new (so it was never not under construction) and I only downloaded the data about 6 weeks ago, but to see if it was merely an error in the old data I removed and purged the docker container and then created it again with a new geofabrik extract.

But unfortunately I've come across a new error which has prevented me from seeing if the new extract worked. Since I'm concerned with the roads, my processing script takes the road id and converts it back into a gid (by subtracting one if odd, and dividing by two), and then matches it against a a list of gids and osm_ids I exported from the the docker container using psql (ie `\copy (select gid, osm_id from bfmap_ways) to gids.csv with csv`). This worked perfectly with the prior extract, but when I try to match this time the process is awry. Matches are clearly wrong, but also a large number of the gids calculated from the ids barefoot returned are larger than any gid in the table exported from the docker container. For instance, with one vehicle barefoot returns 1916 distinct road ids (including imputed ones on the routes) that transform into 1488 distinct gids, of which 472 are higher than 2203202, which is the length of the table exported from the database. 

I'm not sure how this can happen, or why it is only happening now. The only changes are a new extract, with new table export, and updating barefoot to the latest version whilst preserving the changes I made to return road ids.

**Comment by GeoCrunch** [comment]
Having successfully cleared out caches etc I have concluded this is was a data issue (mainly inconsistencies between different forms of the data and a misshapen shapefile) and the import script was working correctly. 

Feel free to close this, and thankyou dearly for your time nonetheless

**Comment by smattheis** [comment]
Glad to hear that it worked out. Thanks, anytime again!
