### ISSUE TITLE
Using barefoot with different maps?

### ISSUE THREAD

**Issue by adng** [bmwcarit/barefoot#60]
Hello,

First, thank you for the great package!

We have an issue when using barefoot with 2 versions of a map. Here is our situation: 
- The map matcher starts processing the first part of a trajectory on the first version of the map (_mapV1_). It produces a map matching state with candidates identified by _id_i_, _id_j_, …
- The map is then updated to _mapV2_. Some elements are added or removed.
- _mapV2_ is imported to the db using barefoot’s script. As the unique id for each element in the db is computed as the count incremented when an element is imported, the uniqueness is guaranteed for each map but there is no mapping between elements of _mapV1_ and _mapV2_. Road _id_i_ in _mapV2_ and in _mapV1_ may be different roads.
- barefoot continues to process the second part of the trajectory on _mapV2_. But It may fail because its candidates don’t correspond to elements found in _mapV2_, or the candidates are missing in _mapV2_.

Do you have any suggestions to solve this problem? 
Thanks for any help or advice.

Best regards.

**Comment by smattheis** [comment]
May I ask, why do you need two versions of a/the map? - Apart from that, if a road is included in both verions of the raw map data it will have the same OSM id in barefoot. Moreover, if there is also no new connection of the road to some other road, source and target points of the road will also have the same OSM ids in both versions. A point on that road (road point) can be matched. However, barefoot's map data structures as is do not provide an efficient search for source and target ids of the roads. Therefore, you can either add such data structure and match it; or, alternatively, perform a radius search on the road map and iterate through the result set to find that road in verion 2 that has the same source and target id as the road in verison 1. With that road and the fraction of the road point, you can now create a road point on version 2 that matches the point.

**Comment by adng** [comment]
Thank you for your response. I thought as well about finding the road in the new map but it adds more complexity and is bug prone. So I think we’ll go for the simple solution by just starting over again from the beginning of the trajectory. 

In fact, the case happens only when we update the raw map data (by importing a new .pbf). Our matchers could be in situations in which they start with the new map and have to continue an on-going matching. So if the ids are not the same across maps, or missing, it could be an error. 

Thanks again for your help. Have a nice day!

**Comment by dvent7** [comment]
To open this issue again instead of writing a new. It often occurs that a map is updated over time. New priorities, changing streets polylines etc. Then the stored kState from previous vehicles can not find the Candid or find the wrong id. Because the IDs have changed, the identifier for a segment (street) should occure twice forward and backward. Could you use the given vector for this problem?
