### ISSUE TITLE
Maxspeed is 0

### ISSUE THREAD

**Issue by dvent7** [bmwcarit/barefoot#68]
I got a NaN exception in filtprob when the maxspeed of a road is 0. Due to not setting the maxspeed of a road the line: the `road.maxspeed()` becomes 0 and the return value NaN

https://github.com/bmwcarit/barefoot/blob/c7b55daab5fe14c3e0b02f9e76e22ca509633ac4/src/main/java/com/bmwcarit/barefoot/roadmap/Time.java#L32

In my opinion here should a default value be applied when maxspeed is not set.

For example 80km/h.

https://github.com/bmwcarit/barefoot/blob/c7b55daab5fe14c3e0b02f9e76e22ca509633ac4/src/main/java/com/bmwcarit/barefoot/roadmap/Road.java#L95-L101

**Comment by smattheis** [comment]
There is a default value for maximum speed of a road. The question is: Why and where is your road's maximum speed is set to '0'?

**Comment by dvent7** [comment]
Where can in find the default value of maxspeed in the BFMapWriter? I made a mistake and did not put a new element in the 
 barefoot/map/tools/road-types.json 

https://github.com/bmwcarit/barefoot/blob/master/map/tools/road-types.json#L1-L106

**Comment by smattheis** [comment]
Unfortunately, that's not possible right now. The default value is used when road data is read initially from the database if a road's maximum speed is set to NULL. After that, road's have a fix assignment of maximum speed such that it's not possible to rewrite the value. Therefore, best way is to delete bfmap file and reread the data from the database (barefoot map server) with the correct road-types.json defined.

**Comment by dvent7** [comment]
OK thank you, iam wondering what is your default value when priority and maximum speed is set to NULL? I could not find part in the code.

**Comment by smattheis** [comment]
Sorry, forgot to mention that. That's not in the code, it's part of road-types.json file. This file is used at two separate points in the Barefoot tool chain. First, to filter road types when parsing OSM data. Second, to use default values when Barefoot reads data from the database.

**Comment by dvent7** [comment]
Oh ok, so `unclassified` is the default value. Thank you
