### ISSUE TITLE
Incorrect matching of noisy data in v-0.1.1

### ISSUE THREAD

**Issue by grigoriytch** [bmwcarit/barefoot#69]
Hi Sebastian,
I have a problem matching some bad quality GPS data with version 0.1.1. Both tests are made with tracker server and version 0.1.0 deals with this perfectly. But in the new version there are same false loop on near streets. Please take a look on the images. I'm attaching the source data also.
![v-0 1 0](https://user-images.githubusercontent.com/20398983/30383743-0df075e6-98ab-11e7-9f63-cc3a32773e51.png)
![v-0 1 1](https://user-images.githubusercontent.com/20398983/30383782-20e3d10c-98ab-11e7-930e-facf96f29d3e.png)
[points.txt](https://github.com/bmwcarit/barefoot/files/1299798/points.txt)

**Comment by smattheis** [comment]
I will do a little debug tour to see if there is a bug or if it's actually the noise which needs a little tuning of the parameters. BTW +1 for providing the data to debug it.

**Comment by smattheis** [comment]
In a first test, I haven't found any bug and I got better matching results if I simply increase matcher.sigma to around 10 - 20 meters. The only mismatch is then around the stadium. How does that work for you?

**Comment by grigoriytch** [comment]
Yes, setting sigma to 15 produces much better results with one break, but it is normal when the GPS positions are far from the road. The important thing is that there are no false paths.
Thank you for your help.
