### ISSUE TITLE
Docker not needed after server launched ?

### ISSUE THREAD

**Issue by inconnu26** [bmwcarit/barefoot#76]
We just need some precisions about the general functioning of the Offline Matcher server.

After having executed the import bash from inside the docker, a ".bfmap" file was created outside of the docker.
This file is then used by the java file ("target/barefoot-0.1.1-matcher-jar-with-dependencies.jar"). This starts a server reachable on port 1234. And it works fine.
But it seems that if we kill and remove the docker, the java server still works fine, and can be restarted anytime since it just uses the ".bfmap" file to work.
Is that expected ? Can we safely destroy any Docker after having created the ".bfmap" file ?

**Comment by smattheis** [comment]
Yes, this is correct. However, if you modify/update Barefoot source code it will be incompatible with the *.bfmap file. In this case, it is necessary to reread data from the Docker map server. That means you could just stop the container (not delete) it if you want to stick with a certain map version. If you don't need a certain map version you could just recreate the map server with a new version of map data. Further, it is more easy to modify map data in the database of the Docker map server as in the program.
