### ISSUE TITLE
mapmatching error response

### ISSUE THREAD

**Issue by aggour211** [bmwcarit/barefoot#84]
Hello,
First of all, i've been using the library for quite some time and it works like a charm, you are doing a great Job. Thank you.
I've found during my tests an issue that cause a mapmatch error. Whenever the trip passes from a lat or lon that are in the range ]-0.1, 0.1[  the server returns an error.

Here are some samples where the problem occurs:
![sans titre 1](https://user-images.githubusercontent.com/32061704/34994621-6ce9feba-fad4-11e7-91b8-f9570a95fcc7.png)

[data.txt](https://github.com/bmwcarit/barefoot/files/1635555/data.txt)
[latlon.txt](https://github.com/bmwcarit/barefoot/files/1635556/latlon.txt)

Thank you a lot,
Issam

**Comment by smattheis** [comment]
Thanks for reporting this issue. I assume that you used the offline matcher. Could you please post the log output of the server for that error?

**Comment by smattheis** [comment]
As said before, to verify the bug the server log output would be good. In turn, to verify the bugfix before I push on the master branch, you could try the following patch [intercept-bugfix.txt](https://github.com/bmwcarit/barefoot/files/1636482/intercept-bugfix.txt) if it fixes the problem for your sample traces. You can apply the bugfix as follows:
``` bash
cd barefoot
git apply path/to/intercept-bugfix.txt
mvn package -DskipTests
```
Thanks!

**Comment by aggour211** [comment]
Thank you very much for your fast response. 
The bugfix works i'll keep testing.
Thanks a lot.
